### ISSUE TITLE
Ubuntu 22

### ISSUE THREAD

**Issue by eawain** [gmazoyer/ansible-role-netbox#18]
Hi mate use your role quite a lot in lab and prod due to its high quality.
On Ubuntu 22 I had to do the following to make it pass on Ubuntu 22 

In gmazoyer.netbox/vars/ 

Had to create a file called ubuntu-22.yml that  I copied from ubuntu.yml in /.ansible/roles/gmazoyer.netbox/vars directory 
ubuntu-22.yml

Changed the following vars due to python changes and package name changes or version changes

__netbox_python_packages:
   \- python3.10                                      # Changed from python3.8
   \- python3.10-dev                               # Changed from python3.8-dev

 __netbox_web_frontend_packages:
   \- libapache2-mod-wsgi-py3                #Changed from     libapache2-mod-wsgi
  
netbox_python_binary: /usr/bin/python3.10

**Comment by gmazoyer** [comment]
Fix in [6dc7a4c](https://github.com/gmazoyer/ansible-role-netbox/commit/6dc7a4cf93fcdf9e4121a528638b2899c0ca4914)
