### ISSUE TITLE
netbox_web_tls in documentation but commit not in latest release

### ISSUE THREAD

**Issue by Charlie-Root** [gmazoyer/ansible-role-netbox#32]
When installing using the latest release the following options seemed to be ignored:
```
netbox_web_tls: false
netbox_web_tls_port: 443

```
it seems that it's mentioned in the documentaiton, but the commit is not present in the latest version.

**Comment by gmazoyer** [comment]
This feature has been released as part of the 3.7.0 version on Ansible Galaxy.
